version: '3'

services:
  db:
    image: postgres
  web:
    build: .


    command: bash -c "python manage.py makemigrations Members Administration Foreman Rtm && python manage.py migrate  && python manage.py runserver 0.0.0.0:8000"


    volumes:
      - .:/cod
    ports:
      - "8000:8000"
    depends_on:
      - db

