# Generated by Django 2.1 on 2019-12-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caprofile',
            name='email_id',
            field=models.EmailField(max_length=150),
        ),
    ]
